### ISSUE TITLE
Outdated libraries

### ISSUE THREAD

**Issue by wistpotion** [ts-defold/tsd-template#35]
Both tstl and ts has received a lot of updates, so an update here would be super nice! Thanks a ton for creating this!

**Comment by thinknathan** [comment]
I'm interested in creating a pull request that will address this issue. I'll prepare something soon.

**Comment by thejustinwalsh** [comment]
https://github.com/ts-defold/tstl-export-as-global/pull/1#issuecomment-1609954501
