### ISSUE TITLE
No matching version found for typescript-tstl-plugin@0.3.0

### ISSUE THREAD

**Issue by PizzaConsole** [ts-defold/tsd-template#61]
No matching version found for typescript-tstl-plugin@0.3.0

Version "typescript-tstl-plugin": "0.3.2" works for me

**Comment by thinknathan** [comment]
The lockfile has it resolved to `0.3.2`. But I guess this is another `pnpm` quirk? I'll explicitly bump the version in `package.json`

Thanks for reporting!
